/**
 * Workflow run context — the state of one task moving through a workflow.
 *
 * The workflow definition (see definition.ts) decides which step runs next;
 * this module holds what a run has accumulated so far and the helpers to
 * create, finish, and inspect it. v1 sessions (state-machine based) are
 * converted on load by `normalizeContext`.
 *
 * Dependency direction: engine.ts → agents/types, agents/verdicts (types)
 * Used by: workflow runner, sessions, CLI commands, TUI
 */

import type { AgentRole } from '../../agents/types.js';
import type { Verdict, VerdictRole } from '../../agents/verdicts.js';

/** Whether a run is still going, or how it ended. */
export type RunStatus = 'running' | 'passed' | 'failed';

/** One executed step. */
export interface StepRecord {
    /** Step id from the workflow definition. */
    step: string;
    agent?: AgentRole;
    /** `passed`: continued normally; `failed`: a check or gate routed to onFail; `aborted`: the run stopped. */
    outcome: 'passed' | 'failed' | 'aborted';
    /** Why the step failed or the run stopped. */
    detail?: string;
    timestamp: number;
}

/** All accumulated data during a workflow run. */
export interface WorkflowContext {
    /** The original task description. */
    task: string;
    /** Name of the workflow definition being run. */
    workflow: string;
    status: RunStatus;
    /** Id of the step to run next; undefined once the run has ended. */
    step?: string;
    /** Number of fix iterations used (each failed check or gate counts one). */
    iteration: number;
    /** Fix iterations allowed before the run fails. */
    maxIterations: number;
    /** Why the run failed, when status is `failed`. */
    failureReason?: string;
    /** Spec generated by the architect agent. */
    spec?: string;
    /** Plan generated by the architect agent. */
    plan?: string;
    /** Latest reply from a code-writing agent (coder or fixer): what it changed. */
    changeSummary?: string;
    /** The most recent failure the fixer should address. Cleared once a fix is applied. */
    lastFailure?: string;
    /** Files created or modified by code-writing agents. */
    generatedFiles: string[];
    /** Review feedback from the reviewer agent. */
    reviewFeedback?: string;
    /** Security findings from the security agent. */
    securityFindings?: string;
    /** Test files generated by the tester agent. */
    testFiles: string[];
    /** Test failure details. */
    testFailures?: string;
    /** Previous check failure outputs (for detecting repeated errors). */
    previousFailures: string[];
    /** Latest structured verdict from each judging agent. */
    verdicts?: Partial<Record<VerdictRole, Verdict>>;
    /** Every executed step, in order. */
    history: StepRecord[];
}

/**
 * Create a new run context for a task.
 *
 * @param firstStep - id of the workflow's first step
 */
export function createWorkflowContext(task: string, workflow: string, firstStep: string, maxIterations: number = 5): WorkflowContext {
    return {
        task,
        workflow,
        status: 'running',
        step: firstStep,
        iteration: 0,
        maxIterations,
        generatedFiles: [],
        testFiles: [],
        previousFailures: [],
        history: [],
    };
}

/** True once a run has passed or failed. */
export function isTerminal(context: Pick<WorkflowContext, 'status'>): boolean {
    return context.status !== 'running';
}

/** Short status for listings: "passed", "failed", or "at <step>". */
export function runLabel(ctx: Pick<WorkflowContext, 'status' | 'step'>): string {
    return ctx.status === 'running' ? `at ${ctx.step ?? '?'}` : ctx.status;
}

/** End a run as failed. */
export function failRun(ctx: WorkflowContext, reason: string): WorkflowContext {
    return { ...ctx, status: 'failed', step: undefined, failureReason: reason };
}

/** Add `files` to a list without duplicates, preserving order. */
export function mergeFiles(existing: readonly string[], files: readonly string[]): string[] {
    return [...new Set([...existing, ...files])];
}

// ── v1 sessions ──

/** v1 state → the `standard` workflow step that would run next. */
const V1_STATE_TO_STEP: Record<string, string | undefined> = {
    idle: 'plan',
    spec_created: 'plan',
    plan_approved: 'implement',
    code_generated: 'review',
    review_done: 'security',
    security_checked: 'test',
    tests_written: 'test',
    tests_passed: 'judge',
    review_rejected: 'fix',
    tests_failed: 'fix',
    fix_applied: 'review',
};

interface V1Context {
    state?: string;
    history?: Array<{ from?: string; to?: string; event?: string; timestamp?: number }>;
}

/**
 * Convert a context loaded from disk to the current shape.
 * v1 contexts (with `state` instead of `status`) map onto the `standard` workflow.
 */
export function normalizeContext(raw: WorkflowContext | (Omit<WorkflowContext, 'status' | 'workflow' | 'history'> & V1Context)): WorkflowContext {
    if ('status' in raw && raw.status) return raw as WorkflowContext;

    const { state = 'idle', history, ...rest } = raw as Omit<WorkflowContext, 'status' | 'workflow' | 'history'> & V1Context;
    const status: RunStatus = state === 'qa_approved' || state === 'complete' ? 'passed' : state === 'failed' ? 'failed' : 'running';

    return {
        ...rest,
        workflow: 'standard',
        status,
        step: status === 'running' ? V1_STATE_TO_STEP[state] : undefined,
        previousFailures: rest.previousFailures ?? [],
        history: (history ?? []).map(h => ({
            step: h.to ?? 'unknown',
            outcome: h.to === 'failed' ? 'aborted' : 'passed',
            detail: h.event,
            timestamp: h.timestamp ?? 0,
        })),
    };
}
